language: python
python: 3.7
install:
  - pip install mkdocs
  - pip install mkdocs-material
before_script:
  - git clone --depth=1 https://github.com/lightyears1998/notebook.git docs
script:
  - mkdocs build
deploy:
  provider: pages
  local_dir: site
  skip_cleanup: true
  github_token:
    secure: UOxw3utRZUNAS3/lmOPMlBBIJHA1YRYocEr8C7W3AlE869pa2OcyfiJNtjDHdYMgixh80lLnvwiQfmTnawG5ww7US6ei5ZQhB//stwWEloqWJqjbiT6mblxBH1TtUtJ84NDgMBWSEPlaZFwbSYL6559eDz0xFRdZoZ5hry5V8tqSWLwPeiMULxMxPb+KI36thZ6dFDYeNCdiVWFM2UJAWeLA6UhUSdnSTOrgiHJ/S+4+hgoFhf8AkH/skMA30lQ24KTvh2C/iKgOD3umXFQxqQnizknm2Dn4nL+z0F6NpYJE/D36iDMaVNU+hib0vZYWWvoz4WlFln+YSDUUCPfHJI4b6gTcWI7aRqGFImOnrT5kDXzHPKeKa8fZkoJI+ptzVsWDT2wyq+7gz5JD2s3CqHGCzlobGeDg7C07r5gfeORSETvttiziRcY27HnqtsWypwk/H89L8UyZpDSRWZWYKANNivrbU3us4GTSUWXMbDUPqJsd876Y/kV+BjHS5d2NSXPFHL8mfef7R7IsKmcZlno5qjO6R5jeGrO/gYcZIwr7qy0m7r8ZctywvPdR9XTBxfbFnrbUsMhXjTGjzN7md4lwnTmqgs4CbqIF55tFJooTSuock3Wn23Z8sR8ccF1tj92UEGjZnrPCXwbga9wb04ImWCbWefON8pyS1WCYzus=
  keep_history: true
  on:
    branch: master
